#!/bin/bash
# 双无人机系统 - 启动速查表

# 颜色定义
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}"
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║           双无人机系统 - ROS启动速查表                        ║"
echo "║                    2026年4月17日                            ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo -e "${NC}"

echo -e "${GREEN}[1] 推荐启动方式 - 一条命令启动全部${NC}"
echo "    roslaunch uav_control start_dual_uav.launch"
echo ""

echo -e "${GREEN}[2] 分步启动方式${NC}"
echo "    终端1 - MAVROS (可选):"
echo "    roslaunch uav_control start_dual_uav_mavros.launch"
echo ""
echo "    终端2 - LIDAR处理 (UAV1):"
echo "    roslaunch fast_lio mapping_mid360.launch uav_name:=uav1"
echo ""
echo "    终端3 - LIDAR处理 (UAV2):"
echo "    roslaunch fast_lio mapping_mid360.launch uav_name:=uav2"
echo ""
echo "    终端4 - 控制节点 (UAV1):"
echo "    roslaunch uav_control control_real_jy2025.launch uav_name:=uav1"
echo ""
echo "    终端5 - 控制节点 (UAV2):"
echo "    roslaunch uav_control control_real_jy2025.launch uav_name:=uav2"
echo ""
echo "    终端6 - 规划节点 (UAV1):"
echo "    roslaunch super_planner jy_real.launch uav_name:=uav1"
echo ""
echo "    终端7 - 规划节点 (UAV2):"
echo "    roslaunch super_planner jy_real.launch uav_name:=uav2"
echo ""

echo -e "${GREEN}[3] 验证命令${NC}"
echo "    查看所有节点:"
echo "    rosnode list"
echo ""
echo "    查看所有主题:"
echo "    rostopic list"
echo ""
echo "    查看UAV1的Odometry:"
echo "    rostopic echo /uav1/Odometry"
echo ""
echo "    查看计算图:"
echo "    rqt_graph"
echo ""

echo -e "${GREEN}[4] 关键主题映射${NC}"
echo "    ┌─ 控制主题"
echo "    │  ├─ /uav1/mavros/state"
echo "    │  ├─ /uav1/mavros/local_position/odom"
echo "    │  └─ /uav1/mavros/setpoint_raw/attitude"
echo "    ├─ 感知主题"
echo "    │  ├─ /uav1/Odometry"
echo "    │  ├─ /uav1/mpc_trajectory"
echo "    │  └─ /uav1/drone_odometry"
echo "    └─ 规划主题"
echo "       ├─ /uav1/planning/pos_cmd"
echo "       ├─ /uav1/planning_cmd/poly_traj"
echo "       └─ /uav1/goal"
echo ""

echo -e "${GREEN}[5] 文件位置快速导航${NC}"
echo "    Launch文件:"
echo "    ├─ control_real_jy2025.launch (控制)"
echo "    ├─ jy_real.launch (规划)"
echo "    ├─ mapping_mid360.launch (LIDAR)"
echo "    ├─ start_dual_uav.launch (双无人机启动)"
echo "    └─ start_dual_uav_mavros.launch (MAVROS配置)"
echo ""
echo "    文档文件:"
echo "    ├─ README_DUAL_UAV.md (详细文档)"
echo "    ├─ QUICK_START.md (快速启动)"
echo "    ├─ MODIFICATION_SUMMARY.md (修改总结)"
echo "    └─ VERIFICATION_REPORT.md (验证报告)"
echo ""

echo -e "${YELLOW}[!] 常见错误排查${NC}"
echo "    ✗ 节点名称冲突"
echo "      → 添加 uav_name:=uav1 或 uav_name:=uav2"
echo ""
echo "    ✗ 无法收到Odometry"
echo "      → 检查 rostopic list | grep Odometry"
echo ""
echo "    ✗ MAVROS无连接"
echo "      → 检查UDP端口配置 (24540/24541)"
echo ""
echo "    ✗ 规划器无输出"
echo "      → 调整 start_x, start_y, start_z 参数"
echo ""

echo -e "${BLUE}更多信息请查看完整文档:${NC}"
echo "  📄 /src/control/uav_control/launch/README_DUAL_UAV.md"
echo "  📄 /src/control/uav_control/launch/QUICK_START.md"
echo ""
